---
abstract: 'drop-in replacement for HTML::Entities'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
  - 'TOBYINK <tobyink@cpan.org>'
build_requires:
  Test::More: '0.61'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.016, CPAN::Meta::Converter version 2.140640'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HTML-HTML5-Entities
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  HTML::HTML5::Entities:
    file: lib/HTML/HTML5/Entities.pm
    version: '0.004'
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/HTML-HTML5-Entities/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=HTML-HTML5-Entities
  homepage: https://metacpan.org/release/HTML-HTML5-Entities
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-html-html5-entities.git
version: '0.004'
